// insert Document in Collection (Single Document)
// db.collection.insert()

// insert Document in Collection (insertMany Document)
// db.collection.insertMany()

// $gt
// $gt is greaterthan


// match used for specify and match a condition
// For example
// {$match :{city:"Chandigarh"}}
// {$match :{age:{$gt: 99}}}
// {$match :{$and: [{gender:"male"},{age;{$gt:25}}]}}

// $group
// get Particular key value from collection 

